### ISSUE TITLE
Research about ingesting flows from github into share-red

### ISSUE THREAD

**Issue by h-parekh** [share-research/SHARE#9]
How would you ingest a flow file in [share-red-flows GitHub repository](https://github.com/share-research/share-red-flows/tree/master/harvest-flows) into a share-red local instance?

**Comment by rickjohnson** [comment]
This has now been merged into master of share-red

**Comment by h-parekh** [comment]
Here's a [youtube link](https://www.youtube.com/watch?v=Bto2rz7bY3g) for reference!
